[package]
name = "zummarai"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
mime = "0.3.17"
sha2 = "0.10.8"
async-trait = "0.1.81"
log = "0.4.22"
env_logger = "0.11.5"
